# Site settings
title: Dispwnl
SEOTitle: A-Failure的博客 | Dispwnl
header-img: img/qaq/009.jpg
email: 2297349251@qq.com
description: "一个天天被吊打小蒟蒻的blog"
url: "https://a-failure.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

catelog: true

# SNS settings
RSS: false
github_username:    A-Failure
# linkedin_username:  firstname-lastname-idxxxx

#gitment
comment_gitment_repo: A-Failure.github.io
comment_gitment_clientId: cbb307ff7e24206d1f4e
comment_gitment_clientSecret: 391f931f64f9c8255dd1e887bedadbf1b5b0263b


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown



# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: auto



# Sidebar settings
sidebar: true                   # whether or not using Sidebar.
sidebar-about-description: "我真是嗨到不行啊"
sidebar-avatar: /img/qaq/1.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
 


# Friends
friends: [
    {
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },{
        title: "xMinh",
        href: "https://xminh.github.io/"
    },{
        title: "Asia",
        href: "http://www.cnblogs.com/victorique/"
    },{
        title: "fuge",
        href: "https://www.cnblogs.com/beretty/"
    },{
        title: "zzzyc",
        href: "https://www.luogu.org/blog/user52892/"
    },{
        title: "Cansult",
        href: "https://www.cansult.ga/"
    },{
        title: "Captain_Paul",
        href: "https://www.luogu.org/blog/Captain-Paul/"
    },{
        title: "AH",
        href: "https://mhrlovezmy.coding.me/"
    },{
        title: "Small_Little_Rabbit",
        href: "https://www.cnblogs.com/Slrslr/"
    },{
        title: "Refun",
        href: "http://www.cnblogs.com/refun/"
    },{
        title: "Milky-Way",
        href: "http://www.cnblogs.com/milky-w/"
    },{
        title: "The_Green_Sun-bGray",
        href: "https://garystack.github.io/"
    },{
        title: "Wzhqwq",
        href: "https://wzhqwq.coding.me/"
    },{
        title: "BigBother",
        href: "https://blog.csdn.net/A_Comme_Amour"
    },{
        title: "Ycr",
        href: "http://ycrpro.com/"
    },{
        title: "Collation&Seek Group",
        href: "http://zwcblog.top./"
    },{
        title: "ljy",
        href: "https://hachimanjy.github.io/"
    },{
        title: "cjc",
        href: "https://comeintocalm.cn/"
    },{
        title: "子谦。",
        href: "http://www.cnblogs.com/hanruyun/"
    },{
        title: "yyb",
        href: "https://www.cnblogs.com/cjyyb/"
    },{
        title: "Dfkdsmbd",
        href: "https://dfkdsmbd.cc/"
    }
]
